// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABwmcyNCp-6agXv0pgs3Rmk-ZTIJ6w5MY',
    appId: '1:616770311264:web:4fdd2c3c5bbc56d7901f05',
    messagingSenderId: '616770311264',
    projectId: 'tar-q-f7b0d',
    authDomain: 'tar-q-f7b0d.firebaseapp.com',
    storageBucket: 'tar-q-f7b0d.appspot.com',
    measurementId: 'G-PTL7KF0MEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLvrz01sIFcXYAQFlUAFtM9o2AFICcRs',
    appId: '1:616770311264:android:73c7eb3f56f24443901f05',
    messagingSenderId: '616770311264',
    projectId: 'tar-q-f7b0d',
    storageBucket: 'tar-q-f7b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzXcgfp1C10tP0MtK3SkDzpvUNhfTDMv8',
    appId: '1:616770311264:ios:255bacefd77b66d5901f05',
    messagingSenderId: '616770311264',
    projectId: 'tar-q-f7b0d',
    storageBucket: 'tar-q-f7b0d.appspot.com',
    androidClientId: '616770311264-m0r0ir712caj5pgg1hsc256s9sjrcihr.apps.googleusercontent.com',
    iosClientId: '616770311264-e2au4ok5r83142k9579lgtdptppg0dqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzXcgfp1C10tP0MtK3SkDzpvUNhfTDMv8',
    appId: '1:616770311264:ios:ff5a03333e498406901f05',
    messagingSenderId: '616770311264',
    projectId: 'tar-q-f7b0d',
    storageBucket: 'tar-q-f7b0d.appspot.com',
    androidClientId: '616770311264-m0r0ir712caj5pgg1hsc256s9sjrcihr.apps.googleusercontent.com',
    iosClientId: '616770311264-9uhn7u17h8offft2pphb6h7akm7o08ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarq.RunnerTests',
  );
}
